# Generated by Django 3.0.5 on 2020-06-26 17:15

import ai_attendance_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_attendance_system', '0004_auto_20200626_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=ai_attendance_system.models.user_directory_path),
        ),
    ]
