# Generated by Django 3.0.5 on 2020-07-02 06:52

import ai_attendance_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_attendance_system', '0013_auto_20200630_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to=ai_attendance_system.models.user_directory_path, width_field=600),
        ),
    ]
