# Generated by Django 3.0.5 on 2020-07-02 07:01

import ai_attendance_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_attendance_system', '0016_auto_20200702_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=ai_attendance_system.models.student_directory_path),
        ),
    ]
